<div id="nuevoregistro">
<h3>Registro de nueva Usuario para el Sistema</h3>
<hr>
<form action="/actor/grabaactor/" method="POST">
	<p>Nombre:<br>
		<input type="text" name="Actor[nombres]"><br>
	</p>
	<p>Apellido Paterno:<br>
		<input type="text" name="Actor[apellidopaterno]"><br>
	</p>
	<p>Apellido Materno:<br>
		<input type="text" name="Actor[apellidomaterno]"><br>
	</p>
	<p>Usuario:<br>
		<input type="text" name="Actor[usuario]"><br>
	</p>
	<p>Generar Contraseña:<br>
		<input type="text" name="Actor[contrasena]"><br>
	</p>
	<p>
	<input type="submit" value="Registrar"><br>
	</p>
	
</form>
</div>