<div id="nuevoregistro">
<h2>Cambio de Clave en el Sistema</h2>
<hr><br><br>
<form method="POST" action="/actor/grabaclave/">
<p>
	Clave Anterior:<br>
	<input type="text" name="claveanterior" autocomplete="off">
</p>

<p>
	Nueva Clave:<br>
	<input type="password" name="clavenueva1">
</p>

<p>
	Repetir Clave :<br>
	<input type="password" name="clavenueva2">
</p>
<p>
	<input type="submit" value="..:::Grabar:::..">
</p>
</form>

</div>