<div id="listados">
<table>
		<caption>Listado de Conceptomovimiento</caption>
		<tr>
			<th>C&oacute;digo</th>
			<th>Nombre</th>
			<th colspan="2">Acci&oacute;n</th>
		</tr>
		<?php
			for($i=0;$i<count($Conceptomovimiento);$i++){
				echo "<tr>";
					echo "<td>".$Conceptomovimiento[$i]['idconceptomovimiento']."</td>";
					echo "<td>".$Conceptomovimiento[$i]['nomconmov']."</td>";
					echo '<td><a href="/conceptomovimiento/editar/'.$Conceptomovimiento[$i]['idconceptomovimiento'].'/'.$Conceptomovimiento[$i]['idtipomovimiento'].'" class="btnEditar"><img src="/imagenes/editar.gif"></a></td>';
					echo "<td><a href=\"/conceptomovimiento/elimina/".$Conceptomovimiento[$i]['idconceptomovimiento']."\" class=\"btnEliminar\"><img src=\"/imagenes/eliminar.gif\"></a></td>";
				echo "</tr>";
			}
		?>
</table>
<a href="/conceptomovimiento/nuevo/"><img src="/imagenes/new.gif"></a>
</div>