<div class="centrarregistro">

	<h3>Ingrese un rol nuevo</h3>

	<form action="/seguridad/grabarol/" method="post" enctype="multipart/form-data" >
	<fieldset>
		<legend>Datos Del Rol</legend>
			
			<p>Nombre Del Rol: 
				<input type="text" name="Rol[nombre]" size="25" />
			</p>
			<p>Descripcion: 
				<input type="text" name="Rol[descripcion]" size="25" />
			</p>
			<input  type="submit" id="enviar" value="Grabar"> 
	</fieldset>
		
	
		</form>
</div>

