<script src="/javascript/marca.js"></script>
<form action="/marca/graba/" method="POST">
	<fieldset>
	<legend>Registro de Nueva Marca</legend>
		<ul>
			<li>
				<label>Nombre</label>
				<input type="text" autofocus required name="marca[nombre]" class="uppercase" size="35px"/ title="Ingrese el nombre de la marca" maxlength="50">
			</li>
			<li>
				<input type="submit" value="Registrar">
				<button id="btncancelar">Cancelar</button>
			</li>
		</ul>
	</fieldset>
</form>