<h2>Mantenimiento: Editar Tipo Operacion</h2>
<input type="hidden" value="<?php echo $titulo; ?>" id="controller">
<script type="text/javascript">
	$(document).ready(function(){
		controller=$('#controller').val();
		$('#cancelar').click(function(e){
			e.preventDefault();
			window.location='/'+controller+'/lista';
		});
	});
</script>

<fieldset>
	<form action="/<?php echo $titulo; ?>/actualizar" method="post">
		<ul class="inline-block">
			<li>
				<input type="hidden" value="<?php echo $data[0]['idtipooperacion']; ?>" name="idobjeto">
				<label>Codigo</label>
				<input readonly type="text" size="10" name="<?php echo $titulo.'[codigotipooperacion]'; ?>"  value="<?php echo $data[0]['codigotipooperacion'] ?>" required>
			</li>
			<li>
				<label>Nombre</label>
				<input required type="text" size="40" name="<?php echo $titulo.'[nombre]'; ?>"  value="<?php echo $data[0]['nombre'] ?>" required>
			</li>
			<li>
				<label >Tipo Movimiento</label>
				<select name="<?php echo $titulo.'[tipomovimiento]'; ?>" disabled>
						<option value="0" ></option>
					<?php if ($data[0]['tipomovimiento']==1){ ?>
						<option value="1" selected>Ingreso</option>
						<option value="2">Salida</option>
					<?php }else if($data[0]['tipomovimiento']==2){ ?>
						<option value="1" >Ingreso</option>
						<option value="2" selected>Salida</option>
					<?php }else{ ?>
						<option value="1" >Ingreso</option>
						<option value="2" >Salida</option>
					<?php } ?>
					
					
				</select>
				
			</li>
			
			<li>
				<input type="submit" value="Grabar">
				<button id="cancelar">Cancelar</button>
			</li>
		</ul>

	</form>
</fieldset>