<script src="/javascript/impresionAutomatica.js"></script>
<link rel="stylesheet" href="/css/impresionBoletas.css"  >

<?php
$max_item_xfactura=$maximoItem;
$cantidad=count($DetalleBoleta);
$pages=$hojas;
?>

<?php

for($z=0;$z<$pages;$z++){
	$minimo=($z)*$max_item_xfactura;
	$maximo=(($minimo+$max_item_xfactura)>$cantidad)?($cantidad):($minimo+$max_item_xfactura);
?>
<div id="impresion">
	<table id="encabezado">
		
		<tr>
			<td style="width:17mm;">&nbsp</td>
			<td style="width:122mm;"><?php echo htmlspecialchars_decode($Boleta[0]['razonsocial'],ENT_QUOTES); ?></td>
			<td style="width:9mm;">&nbsp</td>

			<td colspan="2" style="width:41mm;"><?php echo $Boleta[0]['dni']; ?></td>
		</tr>
		<tr>
			<td style="width:17mm;">&nbsp</td>
			<td style="width:122mm;"><?php echo htmlspecialchars_decode($Boleta[0]['direccion_envio'],ENT_QUOTES); ?></td>
			<td style="width:9mm;"></td>
			<td style="width:15mm;">&nbsp </td>
			<td style="width:24mm;"><?php echo date('d').' &nbsp &nbsp &nbsp'.date('m').' &nbsp &nbsp &nbsp'.date('Y'); ?></td>
		</tr>
	</table >
	<table id="cuerpo">
		
		<tbody>
				<?php if ($maximo>$max_item_xfactura ) { ?>
					
					<tr>
						<td>viene..</td>
					</tr>
				<?php } ?>
			<?php 
			$importetotal=0;
			/*$maximo=25;
			$minimo=0;*/
			//$cantidad=count($DetalleBoleta);
			for ($i=$minimo; $i <$maximo ; $i++) { 
				///if (!empty($DetalleBoleta[$i]['codigopa']) ) { ?>
					
				
			<tr>
				
				<td class="td1"><?php echo $i+1; ?></td>
				<td class="td2"><?php echo substr(htmlspecialchars_decode($DetalleBoleta[$i]['codigopa'],ENT_QUOTES),0,18); ?></td>
				<td class="td3"><?php echo substr(htmlspecialchars_decode($DetalleBoleta[$i]['nompro'],ENT_QUOTES),0,49); ?></td>
				<td class="td4"><?php echo $DetalleBoleta[$i]['cantdespacho']; ?></td>
				<td class="td5"><?php echo  $Boleta[0]['simbolo'].' '.number_format($DetalleBoleta[$i]['preciofinal'],2); ?></td>
				<td class="td6"><?php echo  $Boleta[0]['simbolo'].' '.number_format((($DetalleBoleta[$i]['preciofinal'])*($DetalleBoleta[$i]['cantdespacho'])),2); ?></td>
				<?php $importetotal+=($DetalleBoleta[$i]['preciofinal'])*($DetalleBoleta[$i]['cantdespacho']); ?>

			</tr>
			<?php //} 
			}?>
				<?php if ($cantidad>$maximo && $maximo!=$cantidad) { ?>
					<tr>
						<td colspan="6" style="text-align:center;"><?php echo str_pad('-',150,'-',STR_PAD_LEFT); ?></td>
					</tr>
					<tr>
						<td>va..</td>
					</tr>
				<?php } ?>
				<?php if ($maximo==$cantidad){ ?>
					<tr>
						<td colspan="6"><?php echo str_pad('-',150,'-',STR_PAD_LEFT); ?></td>
					</tr>
				<?php  } ?>
		</tbody>

	</table>

	<table id="piepagina">
		<?php $conversion=$letras->ValorEnLetras(round($importetotal,2),$Boleta[0]['nombresimbolo']); ?>
		<tr>
			<td class="tp1">&nbsp</td>
			<td class="tp2"><?php echo strtoupper($conversion); ?></td>
			<td class="tp3"><?php echo  $Boleta[0]['simbolo'].' '.number_format(($importetotal),2); ?></td>
		</tr>
		
	</table>
</div>

<?php
if(($pages-$z)!=1){

?>
<br style="page-break-before: always;" />
<?php
}
}
?>



