<script src="/javascript/imprimeletras.js"></script>
<div id="imprimirdiv">

	<a href="" id="print" ><img src="/imagenes/imprimir.gif"></a>
	</div>
<?php

$cantidad=count($detalle);
$pages=$cantidad;
?>

<?php

for($z=0;$z<$pages;$z++){
	?>
	<div id="muestra">
		<table id="encabezado" cellspacing="0" cellpadding="0">
			<tr>	
				<td style="width:100px;text-align: center;font-size:12px;"><?php echo $detalle[$z]['numeroletra']; ?> </td>
				<td style="width:100px;text-align: center;font-size:12px;">&nbsp</td>
				<td style="width:100px;text-align:center;font-size:12px;"><?php echo date('d/m/Y',strtotime($detalle[$z]['fechagiro']));  ?> </td>
				<td style="width:80px;text-align:center;font-size:12px;"><?php echo 'LIMA' ?> </td>	
				<td style="width:80px;text-align:center;font-size:12px;"><?php echo date('d/m/Y',strtotime($detalle[$z]['fvencimiento'])); ?> </td>
				<td style="width:100px;text-align:center;font-size:12px;"><?php echo $detalle[$z]['simbolo'];?><?php echo number_format($detalle[$z]['importedoc'],2); ?> </td>
			</tr>
		</table >
		<table id="cuerpoFactura">
			<tr>
				<td colspan="4"  style="width:540px;text-align:center;">&nbsp<?php echo strtoupper($letra->ValorEnLetras(round($detalle[$z]['importedoc'],2),"")); ?><?php echo strtoupper($detalle[$z]['nombre']);?></td>
				<td style="width:35px;text-align:left;">&nbsp;</td>
			</tr>
			<tr>	
				<td colspan="5">&nbsp</td>
			</tr>
			<tr>	
				<td colspan="5">&nbsp</td>
			</tr>
			<tr>
				
				<td colspan="2"  style="height: 24px;width:250px;text-align:left;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo strtoupper(html_entity_decode($detalle[0]['razonsocial'],ENT_QUOTES,'UTF-8')); ?></td>
				<td style="height: 30px;width:100px"></td>
				<td style="height: 30px;width:190px">&nbsp;</td>
				<td style="width:35px;text-align:left;">&nbsp;</td>
			</tr>
			
			<tr>
				<?php $direccion_envio=html_entity_decode($detalle[0]['direccion_envio'],ENT_QUOTES,'UTF-8'); ?>
				<td colspan="4">&nbsp<?php echo strtoupper(substr($direccion_envio,0,42)); ?></td>
				<td style="width:35px;text-align:left;">&nbsp;</td>
			</tr>
			<tr>
				<td colspan="2" style="width:195px;text-align:left;">&nbsp;<?php echo $detalle[0]['nombredepartamento'].'-'.$detalle[0]['nombreprovincia']; ?></td>
				<td colspan="2" style="width:190px;text-align:left;">&nbsp<?php echo $detalle[0]['nombredistrito']; ?></td>
				<td style="width:190px;text-align:left;">&nbsp;</td>
			</tr>
			<tr>
				<td style="width:35px;text-align:left;">&nbsp;</td>
				<td style="width:160px;">&nbsp<?php echo $detalle[0]['ruc']; ?></td> 
				<td style="width:90px;"><?php echo $detalle[0]['telefono']; ?></td>
				<td style="width:100px;text-align:left;">&nbsp;</td>
				<td style="width:190px;text-align:left;">&nbsp;</td>
			</tr>
		</table>

		
	</div>
	 
	<?php
	if(($pages-$z)!=1){
	?>
	<br style="page-break-before: always;" />
	<?php
	}
}
?>



