<script src="/javascript/categoria.js"></script>
<form action="/zona/actualizacategoria/" method="POST">
		 
		
	  	
		
		 <h2><p>EDITAR CATEGORIA:</p></h2>	

			
	
	<ul>	
		<li>
			<select id="lstcategoriapadre" name="Categoria[idpadrec]">
				<?php foreach ($categorias as $catego) { ?>
					
						<?php if ($catego['idcategoria']==$Categoria[0]['idpadrec']) { ?>
							<option value="<?php echo $catego['idcategoria'] ?>" selected><?php echo $catego['nombrec'] ?> </option>
						<?php }else{ ?>
							<option value="<?php echo $catego['idcategoria'] ?>" > <?php echo $catego['nombrec'] ?> </option>

						<?php }?>

					 > <?php  ?> </option>
				<?php }?>
			</select>
		</li>
		
		<li>
			<label>C&oacute;digo</label>
			<input type="text" readonly name="Categoria[codigoc]" value="<?php echo $Categoria[0]['codigoc']; ?>">
		</li>
		<li>
			<label>Nombre</label>
			<input class="required uppercase" required type="text" name="Categoria[nombrec]" value="<?php echo $Categoria[0]['nombrec']; ?>">
		</li>
	</ul>
	<input id="valorId" type="hidden" name="idcategoria" value="<?php echo $Categoria[0]['idcategoria']; ?>">
	<p><input type="submit" value="..::: ACTUALIZAR :::.." ><button id="btnCancelar">Cancelar</button>
		
	</p>
		
</form>