<script src="/javascript/zona.js"></script>
<form action="/zona/graba" method="POST">
	<h2><p>NUEVO CLIENTE - ZONA:</p></h2>
	<ul>
		<li>
			<label>Zona</label>
			<input type="text" name="Zona[idzona]">
		</li>
		<li>
			<label>Cliente</label>
			<input type="text" name="Zona[nombrezona]">
		</li>
		<li>
			<label>Observaci&oacute;n</label>
			<input type="text" name="Zona[observacion]">
		</li>
	</ul>	
	<p><input type="submit" value="..::: REGISTRAR :::.." ><button id="btnCancelar">Cancelar</button></p>
</form>