<form action="/template/graba/" method="POST">
	<ul>
		<li><label>:</label><input type="text" name="Template[apaterno]"></li>
		<li><label>:</label><input type="text" name="Template[amaterno]"></li>
		<li><label>:</label><input type="text" name="Template[nombres]"></li>
		<li><label>:</label><input type="text" name="Template[direccion]"></li>
		<li><label>:</label><input type="text" name="Template[telefono]"></li>
		<li><label>:</label><input type="text" name="Template[email]"></li>
		<li><input type="submit" value="Registrar"></li>
	</ul>
</form>