	<table cellpadding="3" cellspacing="3" border="1">
		<thead>
			<tr>
				<th colspan="3"><h1>BIENVENIDOS AL MINI-FRAMEWORK<BR> :::WEBCONCEPTOS:::</h1></th>
			</tr>
			<tr>
				<td colspan="3"><h3>FELICITACIONES, La configuración se realizó con éxito<br>
								Puedes empezar a utilizar tu plantilla MVC </h3></td>
			</tr>
			<tr>
				<th>Definición/Pregunta</th>
				<th>Descripción/Respuesta</th>
				<th>Otros detalles/Contribuciones</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>Nombre de Framework</td>
				<td>MINI-FRAMEWORK :: WEBCONCEPTOS</td>
				<td>Desarrollado para la introducción a la metodolog{ia de desarrollo denominada Modelo Vista Controlador (MVC)</td>
			</tr>
			<tr>
				<td>¿QUe puedo hacer con esta plantilla?</td>
				<td>La Plantilla MVC :: WebConceptos, te permitirá trabajar con el modelo vista controlador en una manera muy básica</td>
				<td>Desarrollado para la introducción a la metodolog{ia de desarrollo denominada Modelo Vista Controlador (MVC)</td>
			</tr>
			<tr>
				<th colspan="3" align="right">Desarrollado por Fernando Garc&iacute;a At&uacute;ncar , para uso exclusivo en clase.</th>
			</tr>						
		</tbody>
	</table>