<!DOCTYPE HTML>
<html lang="en-ES">
<head>
	<meta charset="UTF-8">
	<title>@CELESTIUM :: Grupo CELESTIUM</title>
	<link type="text/css" href="/css/login.css" rel="stylesheet" >
</head>
<body>
	<div id="login">
		<div class="form"><?php include($path);?></div>
		<div class="pie">&copy; Grupo CELESTIUM - <a href="http://www.webconceptos.com" target="_blank">Desarrollado por WebConceptos</a></div>
	</div>
</body>
</html>