<h2>Mantenimiento: Editar <?php echo $titulo ?></h2>
<input type="hidden" value="<?php echo $titulo; ?>" id="controller">
<script type="text/javascript">
	$(document).ready(function(){
		controller=$('#controller').val();
		$('#cancelar').click(function(e){
			e.preventDefault();
			window.location='/'+controller+'/lista';
		});
	});
</script>
<?php 
	$cantidadBanco=count($banco);
	$cantidadEmpresa=count($empresa);
 ?>
<fieldset>
	<form action="/<?php echo $titulo; ?>/actualizar" method="post">
		<ul class="inline-block">
			<li>
				<input type="hidden" value="<?php echo $data[0]['idctabanco']; ?>" name="idctabanco">
				<label>Nombre</label>
				<input required type="text" name="<?php echo $titulo.'[descripcion]'; ?>"  value="<?php echo $data[0]['descripcion'] ?>" required>
			</li>
			<li>
				<label>Banco</label>
				<select name="<?php echo $titulo.'[idbanco]'; ?>" required>
					<option value="">Seleccione un Banco</option>
					<?php for ($i=0; $i <$cantidadBanco ; $i++) { ?>
					<?php if ($data[0]['idbanco']==$banco[$i]['idbanco']){?>
						<option value="<?php echo $banco[$i]['idbanco']; ?>" selected><?php echo $banco[$i]['descripcion']; ?></option>
					<?php } else{ ?>
						<option value="<?php echo $banco[$i]['idbanco']; ?>"><?php echo $banco[$i]['descripcion']; ?></option>
					<?php }} ?>
				</select>
			</li>
			<li>
				<label>Empresa</label>
				<select name="<?php echo $titulo.'[idempresa]'; ?>" required>
					<option value="">Seleccione una Empresa</option>
					<?php for ($x=0; $x <$cantidadEmpresa ; $x++) { ?>
					<?php if ($data[0]['idempresa']==$empresa[$x]['idalmacen']){ ?>
						<option value="<?php echo $empresa[$x]['idalmacen']; ?>" selected><?php echo $empresa[$x]['razsocalm']; ?></option>
					<?php } else{ ?>
						<option value="<?php echo $empresa[$x]['idalmacen']; ?>"><?php echo $empresa[$x]['razsocalm']; ?></option>	
					<?php } }?>
				</select>
			</li>
			<li>
				<input type="submit" value="Grabar">
				<button id="cancelar">Cancelar</button>
			</li>
		</ul>

	</form>
</fieldset>