
<div id="listados">
<h2>Seguridad: Linea
</h2>
<br>
<form method="POST" action="/linea/buscar/">
<div id="busqueda">
		Busqueda: <br><input type="text" id="txtBusqueda" title="Ingrese un Nombre" name="txtBusqueda" size="50px" value="<?php echo $retorno;?>">
		<input type="submit" value="Ver">
</div>
</form>
<form method="POST" action="/linea/lista/">
		<input type="submit" value="Cancelar">
</form>
<hr>
<table>
	<thead>
		<tr>
			<th colspan="2">Busqueda de Linea</th>
			<th><a href="/linea/nuevo">
					<img src="/imagenes/iconos/nuevo.gif">
				</a></th>
		</tr>
		<tr>
			<th>Código</th>
			<th>Nombre</th>
			<th>Acciones</th>

		</tr>
	</thead>
	<tbody>
		<?php
		$TLinea=sizeof($linea);
		for($i=0;$i<$TLinea;$i++){
			if($linea[$i]['estado']==0){
				$claseinactivo="class=\"inactivo\"";
			}else{
				$claseinactivo="";
			}
			
		$fila="<tr ".$claseinactivo.">";
			$fila.="<td><a href=\"/linea/editar/".$linea[$i]['idlinea']."\">".STRTOUPPER($linea[$i]['idlinea'])."</a></td>";
			$fila.="<td>".$linea[$i]['nomlin']."</td>";
			$fila.="<td width=\"100px\">
						<a href=\"/linea/editar/".$linea[$i]['idlinea']."\" ><img src=\"/imagenes/iconos/editar.gif\"></a>
						<a id='eliminaLinea' value=".$linea[$i]['idlinea']." href=\"/linea/elimina/".$linea[$i]['idlinea']."\" ><img src=\"/imagenes/iconos/eliminar.gif\"></a>";
			$fila.="</td>";
		$fila.="</tr>";
		echo $fila;
		unset($fila);
		}
		?>	
	</tbody>
	<tfoot>
		<tr><td colspan="4" align="center">
		<?php
				$pagina=$_REQUEST['id'];
				if ($blockpaginas*10<$paginacion) {
					$blockpaginas=$blockpaginas+1;
				}else{
					$blockpaginas=$blockpaginas;
				}

				if ($pagina>1) 
				{
					echo "<a href=\"/linea/buscar/".($pagina-1)."\"> "."Anterior"." </a>";
				}
				
				for ($i=1; $i <=$blockpaginas ; $i++) { 
					$max=$i*10;

					for ($min=$max-9; $min <=$max ; $min++) { 
						if ($pagina>=$max-9 && $pagina<=$max && $paginacion>=$min) {
							if ($pagina==$min) {
								echo "<a href=\"/linea/buscar/".($min)."\"> <b style='color:blue;'>".($min)." </b></a>";
							}else{
								echo "<a href=\"/linea/buscar/".($min)."\"> ".($min)." </a>";
							}
						}
					}
				}

				if ($pagina<$paginacion && !empty($pagina)) 
				{
					echo "<a href=\"/linea/buscar/".($pagina+1)."\"> "."Siguiente"." </a>";
				}
				echo 'Total de registros: '.$totregistros;

		?>
		
		</tr>
	</tfoot>
</table>
*Sino puede eliminar una linea es porque esta enlazado
</div>