<script type="text/javascript" src="/javascript/wc_guiamadre.js"></script>
<div id="listados">
<h2>Módulo de Ventas :: Impresión Guia Madre</h2>
<br>
<div id="busqueda">
		Busqueda:<input type="text" id="txtOrdenVenta" name="txtOrdenVenta" size="50px" placeholder="Ingrese el número de orden de venta">
		<input type="hidden" id="txtIdOrden" name="idOrdenVenta" required="required" val="0">
		<button id="imprimir" >Imprimir</button>
		<button id="btnEditarOrdenVenta">Editar Orden Venta</button>
</div>
<br><br>
<div id="muestra">

<style type="text/css">
*{

}
table {
	border: 1px solid;
	border-collapse: collapse;
	border-spacing:0px;
	padding: 0px;
	

	margin: 0px;
}
table tr td, table tr th{
	font-size: 12px;
	
}
</style>
	<div id="">
		
		<div>
			<table id="tblDetalleOrdenVenta">
				<thead>

				</thead>
			</table>
		</div>
		<br>
		
		
		<div id="">

			<table id="tblDetalleOrdenCobro">

				<tbody>
					
				</tbody>
			</table>
		</div>
		<div class="field-set">
			<p class="title">Detalle Orden Venta <span class="addicional-informacion" ></span></p>

			<div id="" class="body"><input type="hidden" value="" class="important">	
				<table id="tblDetalleOrdenVenta2" >
					<tbody>
						
					</tbody>
				</table>
			</div>
		</div>
			<br>
	</div>
</div>
