<script src="/javascript/producto.js"></script>
<h2>Productos :: Editar información </h2>
<form action="/producto/actualiza/" method="POST" id="frmProductoActualiza" enctype="multipart/form-data">
	<fieldset style="position:relative;">
		<legend> Datos de Productos </legend>
		<ul>
			<li>
				<label>C&oacute;digo</label>
				<input type="text"  class="required cod-pro uppercase" name="Producto[codigop]" value="<?php echo $Producto[0]['codigop'] ?>" readonly>
			</li>
			<li>
				<label>C&oacute;digo Fabrica</label>
				<input type="text"  class="required cod-pro uppercase" name="Producto[codigopa]" value="<?php echo $Producto[0]['codigopa'] ?>" readonly>
				<input type="hidden" name="idProducto" value="<?php echo $Producto[0]['idproducto']; ?>">
			</li>
			<li>
				<label>Descripci&oacute;n</label>
				<input type="text" maxlegth="100" class="required nom-pro uppercase text-large" name="Producto[nompro]" value="<?php echo $Producto[0]['nompro'] ?>" autofocus>

			</li>
			<li>
			<div style="position:absolute;right:40px;top:30px;width:180px;text-align:right">
				<?php $imagenReal=ROOT."imagenes".DS."productos".DS.$Producto[0]['codigopa'].DS.$Producto[0]['imagen']; ?>
				<?php $imagenAlterna=$RutaImagen."/sin-imagen.png"; ?>
				<?php $imagenproducto=is_readable($imagenReal)?($RutaImagen.$Producto[0]['codigopa'].'/'.$Producto[0]['imagen']):$imagenAlterna; ?>
				<img src="<?php echo $imagenproducto; ?>" width="180px">
				<p><input type="checkbox" id="chkCambiarFoto"> Cambiar foto</p>
				<input type="file" name="foto" id="fotoProducto" disabled>

			</div>
			<input type="hidden" value="<?php echo $Producto[0]['codigopa']; ?>"  name="Producto[codigopa]">
			</li>		
		</ul>

		<ul>
		<li>
			<label>Almacen</label>
			<select class="required" name="Producto[idalmacen]">
				<?php
					for($i=0;$i<count($Almacen);$i++){
						if($Almacen[$i]['idalmacen']==$Producto[0]['idalmacen']){
							echo '<option selected value="'.$Almacen[$i]['idalmacen'].'">'.$Almacen[$i]['nomalm'].'</option>';
						}else{
							echo '<option value="'.$Almacen[$i]['idalmacen'].'">'.$Almacen[$i]['nomalm'].'</option>';	
						}
					}
				?>
			</select>
		</li>
		<li>
			<label>Linea Productos</label>
			<select id="lstLineaEditar">
				<?php
					for($i=0;$i<count($Linea);$i++){
						if($Linea[$i]['idlinea']==$Sublinea[0]['idpadre']){
							echo '<option value="'.$Linea[$i]['idlinea'].'" selected>'.$Linea[$i]['nomlin'].'</option>';	
						}else{
							echo '<option value="'.$Linea[$i]['idlinea'].'">'.$Linea[$i]['nomlin'].'</option>';
						}
					}
				?>
			</select>
		</li>
		<li>
			<label>Sublinea</label>
			<select class="required" id="lstSublineaEditar"  name="Producto[idlinea]" >
				<?php
					for($i=0;$i<count($Sublinea);$i++){
						if($Sublinea[$i]['idlinea']==$Producto[0]['idlinea']){
							echo '<option value="'.$Sublinea[$i]['idlinea'].'" selected>'.$Sublinea[$i]['nomlin'].'</option>';	
						}else{
							echo '<option value="'.$Sublinea[$i]['idlinea'].'">'.$Sublinea[$i]['nomlin'].'</option>';
						}
					}
				?>
			</select>
		</li>
		</ul>		
		<ul>
		<li>
			<label>Empaque</label>
			<select class="required" name="Producto[empaque]">
				<option value="">Seleccione Empaque
				<?php
					for($i=0;$i<count($Empaque);$i++){
						if($Empaque[$i]['idempaque']==$Producto[0]['empaque']){
							echo '<option selected value="'.$Empaque[$i]['idempaque'].'">'.$Empaque[$i]['codempaque'].'</option>';
						}else{
							echo '<option value="'.$Empaque[$i]['idempaque'].'">'.$Empaque[$i]['codempaque'].'</option>';	
						}
					}
				?>
			</select>
		</li>
		<li>
			<label>Medida</label>
			<select class="required" name="Producto[unidadmedida]">
				<option value="">Seleccione UM
				<?php
					for($i=0;$i<count($Unidadmedida);$i++){
						if($Unidadmedida[$i]['idunidadmedida']==$Producto[0]['unidadmedida']){
							echo '<option selected value="'.$Unidadmedida[$i]['idunidadmedida'].'">'.$Unidadmedida[$i]['nombre'].'</option>';
						}else{
							echo '<option  value="'.$Unidadmedida[$i]['idunidadmedida'].'">'.$Unidadmedida[$i]['nombre'].'</option>';
						}
					}
				?>
			</select>
		</li>
		<li>
		<li>
			<label>Marca</label>
			<select class="required" name="Producto[idmarca]">
					<option value="">Seleccione Marca</option>	
				<?php for ($i=0; $i<count($marca) ; $i++) { 
					if ($Producto[0]['idmarca']==$marca[$i]['idmarca']) {?>
						<option value="<?php echo $marca[$i]['idmarca']; ?>" selected> <?php echo $marca[$i]['nombre']; ?> </option>
				<?php	}else{ ?>
					<option value="<?php echo $marca[$i]['idmarca']; ?>"> <?php echo $marca[$i]['nombre']; ?> </option>
				<?php }}?>
			</select>
		</li>
		
		</ul>
		<!--
		<ul>
			<li>
				<label>Precio Lista</label>
				<input type="text"  class="required cod-pro uppercase" name="Producto[preciolista]" value="<?php echo $Producto[0]['preciolista'] ?>" >
			</li>
			<li>
				<label>Precio Costo</label>
				<input type="text"  class="required cod-pro uppercase" name="Producto[preciocosto]" value="<?php echo $Producto[0]['preciocosto'] ?>" >
			</li>
			<li>
				<label>FOB</label>
				<input type="text"  class="required cod-pro uppercase" name="Producto[fob]" value="<?php echo $Producto[0]['fob'] ?>" >
			</li>
			<li>
				<label>CIF</label>
				<input type="text"  class="required cod-pro uppercase" name="Producto[cif]" value="<?php echo $Producto[0]['cif'] ?>" >
			</li>
			<li>
				<label>Stock Actual</label>
				<input size="8" type="text"  class="required cod-pro uppercase" name="Producto[stockactual]" value="<?php echo $Producto[0]['stockactual'] ?>" >
			</li>
			<li>
				<label>Stock Disponible</label>
				<input size="8"  class="required cod-pro uppercase" name="Producto[stockdisponible]" value="<?php echo $Producto[0]['stockdisponible'] ?>" >
			</li>
		</ul><br>
		|-->
		<ul>
			<li>
				<input type="submit" value="Actualizar">
				<button id="btnCancelar" >Cancelar</button>
			</li>
		</ul>
		

	</fieldset>
</form>