<script src="/javascript/producto.js"></script>
<input type="text" name="" id="txtNombre" value="celestium">
<input type="hidden" id="urlpagination" value="/producto/listar2/">
<table id="grid">     
	 <thead>         
		 <th data-field="nompro">Nombre</th>         
		 <th data-field="stockactual">Stock Actual</th>         
		 <th data-field="stockdisponible">Stock Disponible</th>     
	 </thead>
	 
</table>
<div id="test"></div>
<a href="#" id="btnPrueba">filtrar</a>