<script src="/javascript/producto.js"></script>
<br><br>	

<a href="#" id="imprimir"><img src="/imagenes/imprimir.gif"></a>
<div id="contenedorImpresion">
	<h2>VALORIZADO POR LINEA</h2>
<table>
		<tr>
			<th colspan="3">&nbsp;
		</th>

		</tr>
	<?php 
	$tam=count($datos);
	for ($j=0; $j < $tam; $j++) { 
		# code...
		$graf[$datos[$j]['nomlin']]=$datos[$j]['valorizado'];
		$total+=$datos[$j]['valorizado'];
	}
	for ($i=0; $i < $tam; $i++) { 
	?>
	<tr>
		<td><?php echo $datos[$i]['nomlin'];?></td>
		<td><?php echo " ".number_format($datos[$i]['valorizado'],2) . "\n";;?></td>
		<td rowspan="<?php echo $tam;?>" align="right">
			<?php if($i==0){
				$color = array( '#ccff00', '#7498e9', '#000faa',);
				$date=date('\a \l\a\s g:i a \d\e\l d.m.Y ');
				$grafico->setChartAttrs( 
					array( 	'type' => 'pie', 
							//'title' => 'VALORIZADO POR LINEA al: '.$fecha, 
							'title' => 'VALORIZADO POR CIF VENTAS '.$date, 
							'data' => $graf, 
							'size' => array( 550, 300 ), 
							'color' => $color));	
				echo $grafico;
			} ?>
		</td>
	</tr>
	<?php
	}
	?>
	<tr>
		<td colspan="2"><hr></td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td><?php echo "US $ ".number_format($total,2);?></td>
	</tr>	
</table> 
<?php  
// 			$color = array( '#95b645', '#7498e9', '#000fff',);
// 			$grafico->setChartAttrs( 
// 				array( 	'type' => 'pie', 
// 						//'title' => 'VALORIZADO POR LINEA al: '.$fecha, 
// 						'title' => 'VALORIZADO POR LINEA', 
// 						'data' => $graf, 
// 						'size' => array( 550, 300 ), 
// 						'color' => $color));	
// 			echo $grafico;
?>
</div>
