<script src="/javascript/movimiento.js"></script>
<h2>Almacenes: Movimiento de Stock</h2>
<br>
<div id="listados">
	<form method="POST" action="/almacen/busca/">
	<div id="busqueda">
			Busqueda: </br>
			<input  autofocus="on" type="text" id="txtBusqueda" name="txtBusqueda" size="50px" title="Ingrese una fecha en Formato año/mes/dia o ingrese N° de Documento">
			<input type="submit" value="Ver"/>
	</div>
	</form>

	<table >
		<thead>
			<tr>
				<th colspan="7">Movimiento de Stock</th>
				<th><a href="/movimiento/nuevo/"><img src="/imagenes/iconos/nuevo.gif" style="float:right"></a></th>
			</tr>
			<tr>
				<th>N°</th>
				<th>Tipo</th>
				<th>Concepto</th>
				<th>Fecha</th>
				<th>Serie</th>
				<th>N° Documento</th>
				<th>Observaciones</th>
				<th>Acciones</th>
			</tr>
		</thead>
		<tbody>
			<?php for ($i=0; $i <count($valores) ; $i++) { ?>

			<tr>
				<td style="text-align: center;"><?php echo $valores[$i]['idmovimiento']; ?></td>
				<td style="text-align: center;"><?php echo $valores[$i]['tipomovimiento']; ?></td>
				<td style="text-align: center;"><?php echo $valores[$i]['conceptomovimiento']; ?></td>
				<td style="text-align: center;"><?php echo $valores[$i]['fechamovimiento']; ?></td>
				<td style="text-align: center;"><?php echo $valores[$i]['serie']; ?></td>
				<td style="text-align: center;"><?php echo $valores[$i]['ndocumento']; ?></td>
				<td ><?php echo $valores[$i]['observaciones']; ?></td>
				<td ><a class="detalledelMovimiento" id="<?php echo $valores[$i]['idmovimiento'] ?>" href=""><img style="margin:auto;display:block" title="ver" width="15" high="15" src="/imagenes/ver.gif"> </a> </td>
			</tr>
			<?php	} ?>
		</tbody>
		<tfoot>
			<tr>
			<td colspan="8" align="center">
				<?php
				
				$pagina=$_REQUEST['id'];
				if (empty($_REQUEST['id'])) {
					$pagina=1;
				}
				if ($blockpaginas*10<$paginacion) {
					$blockpaginas=$blockpaginas+1;
				}else{
					$blockpaginas=$blockpaginas;
				}

				if ($pagina>1) 
				{
					echo "<a href=\"/almacen/movstock/".($pagina-1)."\"> "."Anterior"." </a>";
				}
				
				for ($i=1; $i <=$blockpaginas ; $i++) { 
					$max=$i*10;

					for ($min=$max-9; $min <=$max ; $min++) { 
						if ($pagina>=$max-9 && $pagina<=$max && $paginacion>=$min) {
							if ($pagina==$min) {
								echo "<a href=\"/almacen/movstock/".($min)."\"> <b style='color:blue;'>".($min)." </b></a>";
							}else{
								echo "<a href=\"/almacen/movstock/".($min)."\"> ".($min)." </a>";
							}
						}
					}
				}

				if ($pagina<$paginacion && !empty($pagina)) 
				{
					echo "<a href=\"/almacen/movstock/".($pagina+1)."\"> "."Siguiente"." </a>";
				}

		?>
		<select id="seleccion">
			<option value=""></option>
			<?php  for ($i=1; $i <=$paginacion ; $i++) { ?>
				<option value="<?php echo $i; ?>"><?php echo $i; ?></option>
			<?php } ?>
		</select>
		</tr>
			
		</tfoot>
	</table>


</div>
<div id="contenedordetallemovimiento">
	<p>Detalle de Movimiento</p>
	<table id="tablacontenedor">
		<thead>
			<tr>
				<th>Codigo Producto</th>
				<th>Nombre Producto</th>
				<th>Observacion</th>
				<th>Cantidad</th>
			</tr>
		</thead>
		<tbody>


		</tbody>
		<tfoot>

		</tfoot>
	</table>
	<button id="btnCerrarDetalle">Cerrar Detalle</button>
</div>