<script src="/javascript/mantenimiento-cliente.js"></script>
<div id="listados">
<h2>Seguridad: Cliente
</h2>
<br>

<form method="POST" action="/cliente/busca/">
<div id="busqueda">
		Busqueda: <br>
		<input type="text" id="txtBusqueda" name="txtBusqueda" size="50px" title="Ingrese Razon Social o RUC " value="<?php echo $retorno;?>">
		<input type="submit" value="Ver">
			
</div>
</form>
<form method="POST" action="/cliente/lista/">
		<input type="submit" value="Cancelar">
</form>

<table>
	<thead>
		<tr>
			<th colspan="11">Busqueda de Clientes</th>
			<th><a href="/cliente/nuevo">
					<img src="/imagenes/iconos/nuevo.gif">
				</a></th>
		</tr>
		<tr>
			<th>Id</th>
			<th>Razon Social</th>
			<th>DNI</th>
			<th>RUC</th>
			<th>Zona</th>
			<th>Direcci&oacute;n</th>
			<th>E-mail</th>
			<th>Tel&eacute;fono</th>
			<th>Celular</th>
			<th>Fax</th>
			<th colspan="2">Acci&oacute;n</th>

		</tr>
	</thead>
	<tbody>
		
		<tr>
			<?php
			for($i=0;$i<count($Cliente);$i++){
				echo "<tr>";
					echo "<td>".$Cliente[$i]['idcliente']."</td>";
					echo "<td>".$Cliente[$i]['razonsocial']."</td>";
					echo "<td>".$Cliente[$i]['dni']."</td>";
					echo "<td>".$Cliente[$i]['ruc']."</td>";
					echo "<td>".$Cliente[$i]['zona']."</td>";
					echo "<td>".$Cliente[$i]['direccion']."</td>";
					echo "<td>".$Cliente[$i]['email']."</td>";
					echo "<td>".$Cliente[$i]['telefono']."</td>";
					echo "<td>".$Cliente[$i]['celular']."</td>";
					echo "<td>".$Cliente[$i]['fax']."</td>";
					echo "<td><a href=\"/cliente/editar/".$Cliente[$i]['idcliente']."\" class=\"btnEditar\"><img src=\"/imagenes/editar.gif\"></a></td>";
					echo "<td><a href=\"/cliente/eliminar/".$Cliente[$i]['idcliente']."\" class=\"btnEliminar\"><img src=\"/imagenes/eliminar.gif\"></a></td>";
				echo "</tr>";
			}

			?>
		</tr>	
	</tbody>
	<tfoot>
		<tr><td colspan="12" align="center">
		<?php
				$pagina=$_REQUEST['id'];
				if ($blockpaginas*10<$paginacion) {
					$blockpaginas=$blockpaginas+1;
				}else{
					$blockpaginas=$blockpaginas;
				}

				if ($pagina>1) 
				{
					echo "<a href=\"/cliente/busca/".($pagina-1)."\"> "."Anterior"." </a>";
				}
				
				for ($i=1; $i <=$blockpaginas ; $i++) { 
					$max=$i*10;

					for ($min=$max-9; $min <=$max ; $min++) { 
						if ($pagina>=$max-9 && $pagina<=$max && $paginacion>=$min) {
							if ($pagina==$min) {
								echo "<a clas='permanente' href=\"/cliente/busca/".($min)."\"> <b style='color:blue;'>".($min)." </b></a>";
							}else{
								echo "<a clas='permanente' href=\"/cliente/busca/".($min)."\"> ".($min)." </a>";
							}
						}
					}
				}

				if ($pagina<$paginacion && !empty($pagina)) 
				{
					echo "<a href=\"/cliente/busca/".($pagina+1)."\"> "."Siguiente"." </a>";
				}
				echo 'Total de registros: '.$totregistros;

		?>
		
		</tr>
	</tfoot>
</table>
</div>