<script type="text/javascript" src="/javascript/wc_cliente.js"></script>
<div id="listados">
<h2>Clientes :: Vista Global de Cliente</h2>
<br>
<div id="busqueda">
	Busqueda:<input type="text" id="txtClienteGlobal" name="txtCliente" size="50px" placeholder="Ingrese Razón Social o Nro RUC">
<input type="hidden" id="txtIdCliente" name="idcliente">
<br><br>
		Código:<input type="text" name="codigo" readonly id="codigo" disabled> 
		Razon Social:<input type="text" name="razonsocial" readonly id="razonsocial" size="40" disabled> 
		Número de RUC:<input type="text" name="ruc" readonly id="ruc" disabled>
		Codigo Dakkar:<input type="text" name="codantiguo" readonly id="codantiguo" disabled>
	</div>
<br>
<table id="tblOrdenVenta">
	<thead>
		<tr><th colspan="10">Mis Ordenes de Pedido</th></tr>
		<tr>
			<th>Nro Orden</th>
			<th>Fecha<br>Pedido</th>
			<th>Vendedor</th>
			<th>Fecha<br>Despacho</th>
			<th>Monto<br>Total</th>
			<th>Monto<br>Pagado</th>
			<th>Monto<br>Devuelto</th>	
			<th>DEUDA</th>	
			<th>Situación</th>
			<th>&nbsp;</th>
		</tr>
	</thead>	
	<tbody>
	</tbody>
</table>
<br>
<table id="tblDetalleOrdenCobro">
	<tbody>
		
	</tbody>
</table>


