<script src="/javascript/almacen.js"></script>
<input type="hidden" id="urlpagination" value="/almacen/buscar/">
<input type="hidden" id="urleditar" value="/almacen/editar/">
<h2>Mantenimiento: Almacenes</h2>
</br>

<table id="datagridedit">
	<thead>	
		<tr>
			<th data-field="idalmacen">Id</th>
			<th data-field="nomalm">Nombre</th>
			<th data-field="razsocalm">Razon Social</th>
			<th data-field="rucalm">RUC</th>
			<th data-field="diralm">Direcci&oacute;n</th>
		</tr>
	</thead>
</table>
<div class="console"></div>