<h2>Mantenimiento: Clientes</h2>
<input type="hidden" id="urlpagination" value="/cliente/buscar/">
<input type="hidden" id="urleditar" value="/cliente/editar/">
<div align="right" class="bold" style="">
	<a href="/mantenimiento/clientezona">VER CLIENTES - ZONA</a>
	<a href="/cliente/nuevo">
		<img src="/imagenes/iconos/nuevo.gif">
	</a>
</div>
<table id="datagridedit">
	<thead>
		<tr>
			<th data-field="idcliente">Id</th>
			<th data-field="razonsocial">Raz&oacute;n Social</th>
			<th data-field="ruc">RUC</th>
			<th data-field="codantiguo">Codigo Antiguo</th>
			<th data-field="telefono">Telefono</th>
			<th data-field="celular">Celular</th>
			<th data-field="fax">FAX</th>
			<th data-field="email">Email</th>
			<th data-field="dni">Dni</th>
			<th data-field="paginaweb">Pagina Web</th>
			<th data-field="inicioactividades">Inicio Actividades</th>
		</tr>
	</thead>
</table>