<h2>Mantenimiento: Productos</h2> 
<input type="hidden" id="urlpagination" value="/producto/busqueda/">
<input type="hidden" id="urleditar" value="/producto/editar/">
<table id="datagridedit">
	<thead>
		<tr>
			<th data-field='idproducto'>Id</th>
			<th data-field='codigopa'>Foto</th>
			<th data-field='codigop'>Codigo</th>
			<th data-field='nompro'>Nombre</th>
			<th data-field='stockactual'>Stock Actual</th>
			<th data-field='stockdisponible'>Stock Disponible</th>
			<th data-field='fechaingreso'>Fecha Ingreso</th>
			<th data-field='marca'>Marca</th>
			<th data-field='fob'>FOB</th>
			<th data-field='cif'>CIF</th>
			<th data-field='preciolista'>Precio Lista</th>
			<th data-field='preciocosto'>Precio Costo</th>
		</tr>
	</thead>
</table>