<script src="/javascript/proveedor.js"></script>
<input type="hidden" id="urlpagination" value="/proveedor/buscar/">
<input type="hidden" id="urleditar" value="/proveedor/editar/">
<h2>Mantenimiento: Proveedores</h2>
<table id="datagridedit">
	<thead>
		<tr>
			<th data-field="idproveedor">Id</th>
			<th data-field="razonsocialp">Raz&oacute;n Social</th>
			<th data-field="rucp">RUC</th>
			<th data-field="emailp">E-mail</th>
			<th data-field="telefonop">Tel&eacute;fono</th>
			<th data-field="telefonop2">Celular</th>
			<th data-field="faxp">Fax</th>
		</tr>
	</thead>
</table>