<script src="/javascript/transporte.js"></script>
<input type="hidden" id="urlpagination" value="/transporte/buscar/">
<input type="hidden" id="urleditar" value="/transporte/editar/">
<h2>Mantenimiento: Transportes</h2> 
<table id="datagridedit">
	<thead>
		<tr>
			<th data-field="idtransporte">Id</th>
			<th data-field="trazonsocial">Nombre</th>
			<th data-field="tdireccion">Direcci&oacute;n</th>
			<th data-field="ttelefono">Telefono</th>
			<th data-field="truc">RUC</th>
		</tr>
	</thead>
</table>