<input type="hidden" id="urlpagination" value="/vendedor/buscar/">
<input type="hidden" id="urleditar" value="/vendedor/editar/">
<h2>Mantenimiento: Vendedores</h2>
<table id="datagridedit">
	<thead>
		<tr>
			<th data-field="idactor">Id</th>
			<th data-field="nombreconcat">Nombre Completo</th>
			<th data-field="direccion">Direcci&oacute;n</th>
			<th data-field="telefono">Telefono</th>
			<th data-field="celular">Celular</th>
			<th data-field="rpm">RPM</th>
			<th data-field="codigoa">Codigo Antiguo</th>
			<th data-field="email">Email</th>
			<th data-field="dni">Dni</th>
		</tr>
	</thead>
</table>