<script src="/javascript/devolucion.js"></script>
<h2>Lista de Devoluciones</h2>
<?php $cantidadDevoluciones=count($dataDevolucion); ?>
<fieldset>
	<form method="POST" action="/devolucion/buscaDevoluciones/">
	<div id="busqueda">
			Busqueda: </br>
			<input type="text"  id="txtBusqueda" name="txtBusqueda" size="50px" title="Ingrese Orden Venta o Número de Devolucion" autofocus="on">
			<input type="submit" value="Ver"/>
	</div>
	</form>
	<table>
		<thead>
			<tr>
				<th rowspan="2">N°</th>
				<th rowspan="2">Orden Venta</th>
				<th rowspan="2">Importe Total</th>
				<th rowspan="2">Fecha Aprobada</th>
				<th rowspan="2">Fecha Registrada</th>
				<th colspan="2">Acciones</th>
			</tr>
			<tr>
				<th>Tiene Factura</th>
				<th>ver</th>
				
			</tr>
		</thead>
		<tbody>
			<?php for ($i=0; $i <$cantidadDevoluciones ; $i++) { ?>
				<tr>
					<td style="text-align: center;"><?php echo $dataDevolucion[$i]['iddevolucion']; ?></td>
					<td style="text-align: center;"><?php echo $dataDevolucion[$i]['codigov']; ?></td>
					<td style="text-align: right;"><?php echo $dataDevolucion[$i]['simbolo']; ?>  <?php echo $dataDevolucion[$i]['importetotal']; ?></td>
					<td style="text-align: center;"><?php echo $dataDevolucion[$i]['fechaaprobada']; ?></td>
					<td style="text-align: center;"><?php echo $dataDevolucion[$i]['fecharegistrada']; ?></td>
					<td><?php echo $dataDevolucion[$i]['esfacturado']; ?></td>
					<td colspan=""><a  class="verdetalle" id="<?php echo $dataDevolucion[$i]['iddevolucion']; ?>" href=""><img style="margin:auto;display:block" width="20" high="20" src="/public/imagenes/ver.gif" ></a></td>
					
				</tr>
			<?php } ?>
			
		</tbody>
		<tfoot>
			<tr>
			<td colspan="15" align="center">
				<?php
				if (empty($_REQUEST['id'])) {
					$pagina=1;
				}else{
					$pagina=$_REQUEST['id'];	
				}
				
				if ($blockpaginas*10<$paginacion) {
					$blockpaginas=$blockpaginas+1;
				}else{
					$blockpaginas=$blockpaginas;
				}

				if ($pagina>1) 
				{
					echo "<a href=\"/devolucion/listarDevolucionTotal/".($pagina-1)."\"> "."Anterior"." </a>";
				}
				
				for ($i=1; $i <=$blockpaginas ; $i++) { 
					$max=$i*10;

					for ($min=$max-9; $min <=$max ; $min++) { 
						if ($pagina>=$max-9 && $pagina<=$max && $paginacion>=$min) {
							if ($pagina==$min) {
								echo "<a href=\"/devolucion/listarDevolucionTotal/".($min)."\"> <b style='color:blue;'>".($min)." </b></a>";
							}else{
								echo "<a href=\"/devolucion/listarDevolucionTotal/".($min)."\"> ".($min)." </a>";
							}
						}
					}
				}

				if ($pagina<$paginacion) 
				{
					echo "<a href=\"/devolucion/listarDevolucionTotal/".($pagina+1)."\"> "."Siguiente"." </a>";
				}

				?>
				<select id="seleccion" >
					<option value=""></option>
					<?php  for ($i=1; $i <=$paginacion ; $i++) { ?>
						<option value="<?php echo $i; ?>"><?php echo $i; ?></option>
					<?php } ?>
				</select>
			</td>
		</tr>
		</tfoot>

	</table>
	<div id="detalle">
		<a id="imprimir" href="#" ><img src="/imagenes/imprimir.gif"></a>
		
		<style type="text/css">
		*{

		}
		table {
			border: 1px solid;
			border-collapse: collapse;
			border-spacing:0px;
			padding: 0px;
			

			margin: 0px;
		}
		table tr td, table tr th{
			
		}
		</style>

	<b id="mensaje"></b>
	<table id="tblEncabezado" sytle="magin-botton:0px"></table>
	<table id="tbldetalles">
		<thead>
			<tr>
				<th>Numero de Devolucion</th>
				<th>Codigo</th>
				<th>Nombre</th>
				<th>Precio</th>
				<th>Cantidad</th>
				<th>Importe</th>
			</tr>			
		</thead>
		<tbody>
			<td></td>
		</tbody>
		<tfoot>
			<td></td>
		</tfoot>
	</table>
<button id="btncerrar">Cerrar Detalle</button>
</div>
</fieldset>
