<script type="text/javascript" src="/javascript/reporteventas.js"></script>
<h2>Reporte :: Ventas</h2>
<fieldset>
<legend></legend>
<form id="Parametros" action="/pdf/reporteventas/" method="post" target="_blank">
	<ul>
		<li>
			<label>Fecha Guiado Inicio</label>
			<input style="background:pink;" type="text" id="txtFechaGuiadoInicio" name="txtFechaGuiadoInicio" class="datepicker" readonly>
		</li>
		<li>
			<label>Fecha Guiado Fin</label>
			<input style="background:pink;" type="text" id="txtFechaGuiadoFin" name="txtFechaGuiadoFin" class="datepicker" readonly>
		</li>
		<li>
			<label>Fecha Despacho Inicio</label>
			<input style="background:skyblue;" type="text" id="txtFechaDespachoInicio" name="txtFechaDespachoInicio" class="datepicker" readonly>
		</li>
		<li>
			<label>Fecha Despacho Fin</label>
			<input style="background:skyblue;" type="text" id="txtFechaDespachoFin" name="txtFechaDespachoFin" class="datepicker" readonly>
		</li>
		<li>
			<label>Pendiente</label>
			<input type="checkbox" name="pendiente" value="1">
		</li>
		<li>
			<label>Fecha Cancelado Inicio</label>
			<input style="background:#9FFF6A;" type="text" id="txtFechaCanceladoInicio" name="txtFechaCanceladoInicio" class="datepicker" readonly>
		</li>
		<li>
			<label>Fecha Cancelado Fin</label>
			<input style="background:#9FFF6A;" type="text" id="txtFechaCanceladoFin" name="txtFechaCanceladoFin" class="datepicker" readonly>
		</li>
		<li>
			<label>Fecha Aprobado Inicio</label>
			<input style="background:#F7E816;" type="text" id="txtFechaAprobadoInicio" name="txtFechaAprobadoInicio" class="datepicker" readonly>
		</li>
		<li>
			<label>Fecha Aprobado Fin</label>
			<input style="background:#F7E816;" type="text" id="txtFechaAprobadoFinal" name="txtFechaAprobadoFinal" class="datepicker" readonly>
		</li>
	</ul>
	<br>
	<ul>
		<li>
			<label>Orden de Venta</label>
			<input type="text" id="txtOrdenVenta" name="txtOrdenVenta" class="uppercase text-300">
			<input type="hidden" id="idOrdenVenta" name="idOrdenVenta">
		</li>
		<li>
			<label>Cliente</label>
			<input type="text" id="txtCliente" name="txtCliente" class="uppercase text-300" >
			<input type="hidden" id="idCliente" name="idCliente">
		</li>
		<li>
			<label>Vendedor</label>
			<input type="text" id="txtVendedor" name="txtVendedor" class="uppercase text-300" >
			<input type="hidden" id="idVendedor" name="idVendedor">
		</li>

	</ul>
	<br>
	<ul>
		<li>
			<label>Zona Geografica</label>
			<select id="lstCategoriaPrincipal" name="idpadre">
				<option value="">Seleccione Zona Geografica</option>
				<?php $cantidadPrincipal=count($categoriaPrincipal) ?>
				<?php for ($i=0; $i <$cantidadPrincipal ; $i++) { ?>
					<option value="<?php echo $categoriaPrincipal[$i]['idcategoria'] ?>"><?php echo $categoriaPrincipal[$i]['nombrec'] ?></option>
				<?php } ?>
			</select>
		</li>
		<li>
			<label>Region Cobranza</label>
			<select id="lstRegionCobranza" name="idcategoria">
				<option value="">Zona Cobranza-Categoria</option>
			</select>
		</li>
		<li>
			<label>Zona</label>
			<select id="lstZona" name="idzona">
				<option value="">Zona Cobranza-Detalle</option>
			</select>
		</li>
		<li>
			<label>Condicion Venta</label>
			<select id="lstCondicion" name="condicion" disabled="disabled">
				<option value="">Seleccione Condicion</option>
				<?php $cantidadCondicion=count($condicionVenta); ?>
				<?php for ($i=1; $i <$cantidadCondicion+1 ; $i++) { ?>
					<option value="<?php echo $i ?>"><?php echo $condicionVenta[$i] ?></option>
				<?php } ?>
			</select>
		</li>
		
		<li>
			<label>Aprobados</label>
			<input type="checkbox" id="aprobados" name="aprobados" value="1">
		</li>
		<li>
			<label>Desaprobados</label>
			<input type="checkbox" id="desaprobados" name="desaprobados" value="1">
		</li>
		<li>
			<label>Moneda</label>
				<select name="idmoneda" id="txtMoneda">
					<option value="-1">Seleccione Moneda</option>
					<option value="1">Soles (S/.)</option>
					<option value="2">Dolares (US $)</option>
				</select>
		</li>		
	</ul>
	<ul>
		<li><button id="btnConsultar" style="font-size: 18px;">Consultar <img style="vertical-align: middle;text-align: center;" width="25" heigth="25" src="/imagenes/consultar.png"></button></li>
		<li><button id="btnLimpiar" style="font-size: 18px;">Limpiar <img style="vertical-align: middle;text-align: center;" width="25" heigth="25" src="/imagenes/limpiar.png"> </button></li>
		<li><button id="btnImprimir" style="font-size: 18px;">Imprimir <img style="vertical-align: middle;text-align: center;" width="25" heigth="25" src="/imagenes/imprimir.gif"> </button></li>
		<li><button id="btnPDF" style="font-size: 18px;">Ver PDF <img style="vertical-align: middle;text-align: center;" width="23" heigth="23" src="/imagenes/iconos/pdf.gif"> </button></li>
		<li><button id="btnRanking" style="font-size: 18px;">Ranking<img style="vertical-align: middle;text-align: center;"  width="50px" height="25px" src="/imagenes/ranking.png"> </button></li>
	</ul>
	

</form>

</fieldset>
<fieldset>
<div id="imprimir">
	<table id="cabecera" style="display:none;">
		<thead>
			<tr>
				<th style="width:15%">Fecha Guiado</th><td><label class="encabezado" id="lblFechaGuiado"></label></td><th style="width:15%">Fecha Despacho</th><td style="width:15%"><label class="encabezado" id="lblFechaDespacho"></label></td><th style="width:15%">Fecha Cancelado</th><td style="width:15%"><label class="encabezado" id="lblFechaCancelado"></label></td>
			</tr>
			<tr>
				<th style="width:15%">Fecha Aprobado</th><td><label class="encabezado" id="lblFechaAprobado" ></label></td><th style="width:15%"></th><td style="width:15%"><label class="encabezado" ></label></td><th style="width:15%"></th><td style="width:15%"><label class="encabezado" ></label></td>
			</tr>
			<tr>
				<th>Orden de Venta</th><td><label class="encabezado" id="lblOrdenVenta"></label></td><th>Nombre de Cliente</th><td><label class="encabezado" id="lblCliente"></label></td><th>Nombre de Vendedor</th><td><label class="encabezado" id="lblVendedor"></label></td>
			</tr>
			<tr>
				<th>Zona Geografica</th><td><label class="encabezado" id="lblZonaGeografica"></label></td><th>Region Cobranza</th><td><label class="encabezado" id="lblRegionCobranza"></label></td><th>Zona</th><td><label class="encabezado" id="lblZona"></label></td>
			</tr>
			<tr>
				<th>Condicion de Venta</th><td><label class="encabezado" id="lblCondicion"></label></td><th>Condicion de la Orden</th><td><label class="encabezado" id="lblCondicionOrden"></label></td>
			</tr>
		</thead>
	</table>
	<table id="tblVentas" style="display:none;">
		<thead>
			<tr>
				<th>Fecha Guiado</th>
				<th>Fecha Despacho</th>
				<th>Fecha Cancelado</th>
				<th>Orden venta</th>
				<th>Nombre Cliente</th>
				<th>Nombre Vendedor</th>
				<th>Importe Aprobado S/.</th>
				<th>Importe Despachado S/.</th>
				<th>Estado</th>
				<th>Condicion Venta</th>
				<th>Detalle</th>
				<th>Situacion</th>
			</tr>
		</thead>
		<tbody></tbody>

	</table>

</div>

</fieldset>
