<script type="text/javascript" src="/javascript/reporteInventario.js" ></script>
<h2>Reporte :: Inventario</h2>
<fieldset>
	<form action="/pdf/reporteInventario" method="post" target="_blank">
		<ul>
			<li>
				<?php $cantidadInventario=count($inventario); ?>
				<label>Inventario</label>
				<select id="lstInventario" name="lstInventario">
					<?php for ($i=0; $i <$cantidadInventario ; $i++) { ?>
						<option value="<?php echo $inventario[$i]['idinventario'] ?>" ><?php echo $inventario[$i]['codigoinv'] ?></option>
					<?php } ?>
				</select>
			</li>
			<li>
				<?php $cantidadBloques=count($bloques); ?>
				<label>Ubicacion</label>
				<select id="lstBloques" name="lstBloques">
					<option value=''>Seleccione Ubicacion</option>
					<?php for ($i=0; $i <$cantidadBloques ; $i++) { ?>
						<option value="<?php echo $bloques[$i]['idbloque'] ?>" ><?php echo $bloques[$i]['codigo'] ?></option>
					<?php } ?>
				</select>
			</li>
			<li>
				<label>Codigo</label>
				<input type="text" size="25" id="txtProducto">
				<input type="hidden" id="idProducto" name="idProducto">
			</li>
			<li>
				<label>Descripcion</label>
				<input type="text" size="65" id="txtDescripcion" readonly>
			</li>
			<li>
				<input type="submit" value="Consultar" id="btnConsultar">
			</li>
			<li>
				<button id="btnLimpiar">Limpiar</button>
			</li>
			
		</ul>
	</form>
</fieldset>