<script type="text/javascript" src="/javascript/reportletras.js"></script>
<script src="/javascript/wc_cliente.js"></script>
<script src="/javascript/wc_ordenventa.js"></script>
<h2>Reporte de Cobranzas</h2>


<fieldset id="listas" >
	<form>
		<?php 
			$cantidadpadre=count($padre);
			$cantidadhijo=count($hijo);
			$cantidadzona=count($zona);
			$cantidadtipo=count($tipocobranza);
			$cantidadvendedor=count($vendedor);
			$cantidadcobrador=count($cobrador);
		 ?>
		<ul>
		 	<li>
				<select id="lstCategoriaPrincipal" >
					<option value="">Zona Geografica</option>
					<?php for ($i=0; $i <$cantidadpadre ; $i++) { ?>
						<option value="<?php echo $padre[$i]['idcategoria']; ?>"><?php echo $padre[$i]['nombrec']; ?></option>
					<?php } ?>
				</select>
			</li>
			<li>
				<select id="lstCategoria" >
					<option value="">Zona Cobranza-Categoria</option>
					<?php for ($i=0; $i <$cantidadhijo ; $i++) { ?>
						<option value="<?php echo $hijo[$i]['idcategoria']; ?>"><?php echo $hijo[$i]['nombrec']; ?></option>
					<?php } ?>
				</select>
			</li>
			<li>
				<select id="lstZona" >
					<option value="">Zona Cobranza-Detalle</option>
					<?php for ($i=0; $i <$cantidadzona ; $i++) { ?>
						<option value="<?php echo $zona[$i]['idzona']; ?>"><?php echo $zona[$i]['nombrezona']; ?></option>
					<?php } ?>
				</select>
			</li>
			<li>
				<select id="lstcobrador" >
					<option value="">Cobrador</option>
					<?php for ($i=0; $i <$cantidadcobrador ; $i++) { ?>
						<option value="<?php echo $cobrador[$i]['idactor']; ?>"><?php echo $cobrador[$i]['nombres'].' '.$cobrador[$i]['apellidopaterno'].' '.$cobrador[$i]['apellidomaterno']; ?></option>
					<?php } ?>
				</select>
			</li>
		</ul>
		<br>
		<ul>
			<li>
				<select id="lstTipoCobranza" >
					<option value="">Tipo Cobranza</option>
					<?php for ($i=0; $i <$cantidadtipo ; $i++) { ?>
						<option value="<?php echo $tipocobranza[$i]['idtipocobranza']; ?>"><?php echo $tipocobranza[$i]['nombre']; ?></option>
					<?php } ?>
				</select>
			</li>
			<li>
				<select id="lstvendedor" >
					<option value="">Vendedor</option>
					<?php for ($i=0; $i <$cantidadvendedor ; $i++) { ?>
						<option value="<?php echo $vendedor[$i]['idactor']; ?>"><?php echo $vendedor[$i]['nombres'].' '.$vendedor[$i]['apellidopaterno'].' '.$vendedor[$i]['apellidomaterno']; ?></option>
					<?php } ?>
				</select>
			</li>
			<li>
				<select id="lstTipoCobro" >
					<option value="">Tipo Cobro</option>
					<option value="1">Contado</option>
					<option value="2">Credito</option>
					<option Value="3">Letras Banco</option>
					<option Value="4">Letras Cartera</option>
				</select>
			</li>
			
		</ul><br>
		<ul>
			<li>
				<label for="txtClientexIdCliente">Razon Social Cliente</label>
				<input type="text" id="txtClientexIdCliente" size="50">
				<input type="hidden" id="txtIdCliente">
			</li>		
			<li>
				<label for="txtOrdenVentaxId">Orden de Venta</label>
				<input type="text" id="txtOrdenVentaxId" size="20">
				<input type="hidden" id="txtIdOrdenVenta">
			</li>	
		</ul>
		<br>
		<ul>
			<li>
				<input style="background:pink" type="text" id="fechaInicio" placeholder="Fecha Vencimi. Inicio" readonly autocomplete="off" >
			</li>
			<li>
				<input style="background:pink" type="text" id="fechaFinal" placeholder="Fecha Vencimi. Final" readonly autocomplete="off" >
				<input type="hidden" value="1" id="valoropcional">
			</li>
			<li>
				<input disabled="disabled" style="background:silver" type="text" id="fechaPagoInicio" placeholder="Fecha Pago Inicio" readonly autocomplete="off" >
			</li>
			<li>
				<input disabled="disabled" style="background:silver" type="text" id="fechaPagoFinal" placeholder="Fecha Pago Final" readonly autocomplete="off" >
				
			</li>
		</ul>
	
</fieldset>
<fieldset>

	<ul>
		<li>
			Pendiente <input type="checkbox" id="pendiente" Style="margin-right:20px;margin-left:5px;" >
		</li>
		<li>
			Cancelado <input type="checkbox" id="cancelado" Style="margin-right:20px;margin-left:5px;">
		</li>
		<li>
			Octavas<input type="checkbox" id="octava" Style="margin-right:20px;margin-left:5px;" disabled="disabled">
		</li>
		<li>
			Novenas<input type="checkbox" id="novena" Style="margin-right:20px;margin-left:5px;" disabled="disabled">
		</li>
		<li>
			<button id="enviar" >Aceptar</button>
		</li>
		<li>
			<button id="imprimir" >Imprimir</button>
		</li>
		<li>
			<input type="reset" id="btnLimpiar" value="Limpiar">
		</li>
	</ul>
	</form>
</fieldset>	

<fieldset id="muestra">

<style type="text/css">
*{

}

table tr td, table tr th{
	font-size: 10px;
	/*font-family: fixedsys, consolas, monospace;*/
	margin: 0px;
	border-collapse: collapse;
}
table tr td, table tr th{
	font-weight: 2px;
}

.tblchildren,.filaOculta{

background-color : rgb(124, 180, 224);
border : none ;
/*font-family: fixedsys, consolas, monospace;*/
border-collapse: collapse;

font-size : 7px;
padding-left : 5px;
padding-right : 5px;
}

</style>
	<table>
		<tr><th colspan="5"><h2>Reporte de Cobranza</h2></th><th>Fecha Impresion: <?php echo date('d-m-Y'); ?></th></tr>
		<tr>
			
			<th>Zona Geografica : </th><td style="background:white;"><label id="txtZonaGeografica"></label></td>
			<th>Zona Cobranza - Categoria : </th><td style="background:white;"><label id="txtZonaCobranza"></label></td>
			<th>Zona Cobranza - Detalle : </th><td style="background: white;"><label id="txtZona"></label></td>
		</tr>
		<tr>
			<th>Tipo Cobranza : </th><td  style="background:white;"><label id="txtTipoCobranza"></label></td>
			<th>Vendedor : </th><td style="background:white;"><label  id="txtVendedor" ></label></td>
			<th>Cobrador : </th><td style="background:white;"><label  id="txtCobrador" ></label></td>
		</tr>
		<tr>
			<th>Tipo Cobro : </th><td style="background: white;"><label id="txtTipoCobro"></label></td>
			<th>Del : </th><td style="background: white;"><label id="txtFechaInicio"></label></td>
			<th>Al : </th><td style="background: white;"><label id="txtFechaFinal"></label></td>
		</tr>
		<tr>
			<th>Situacion : </th>
			<td ><label id="txtOctavas"></label><label id="txtNovenas"></label><label id="txtPendiente"></label><label id="txtCancelado"></label></td>
			<th>Cliente</th><td><label id="txtCliente"></td>
			<th>Orden de Venta</th><td><label id="txtOrdenVenta"></td>
		</tr>
	</table>
	<br>
	<table id="tblreportes" style="width:100%;">
		
	</table>
</fieldset>