<script src="/javascript/stockproducto.js"></script>
<h2>Reportes: Stock de Productos</h2>
<br>
<fieldset style="display:inline-block">
	<legend>Filtro</legend>
	<ul>
		<li>
			<label>Seleccione una de las opiones</label>
			<input type="radio" name="rbFiltro" value="1" checked> Todo
			<input type="radio" name="rbFiltro" value="2"> Por Almacen
			<input type="radio" name="rbFiltro" value="3"> Por Linea
			&nbsp;<input type="radio" name="rbFiltro" value="4"> Por Sub Linea	
			&nbsp;<input type="radio" name="rbFiltro" value="5"> Por Producto
		</li>
		<li id="liAlmacen">
			<label>Almacen</label>
			<select id="lstAlmacen">
				<option value="">-- Almacen --</option>
				<?php
					for($i=0;$i<count($Almacen);$i++){
						echo '<option value="'.$Almacen[$i]['idalmacen'].'">'.$Almacen[$i]['nomalm'].'</option>';
					}
				?>
			</select>
		</li>
		<li id="liLinea">
			<label>Linea</label>
			<select id="lstLinea">
				<option value="">-- Linea --</option>
				<?php
					for($i=0;$i<count($Linea);$i++){
						echo '<option value="'.$Linea[$i]['idlinea'].'">'.$Linea[$i]['nomlin'].'</option>';
					}
				?>
			</select>
		</li>
		<li id="liSubLinea">
			<label>Sublinea</label>
			<select id="lstSubLinea">
				<option value="">-- Sub Linea --</option>
			</select>
		</li>
		<li id="liProducto">
			<label>Producto</label>
			<input type="text" class="text-large required uppercase" placeholder="Ingrese Codigo o Nombre del Producto" id="txtCodigoProducto">
			<input type="hidden" id="txtIdProducto">
		</li>
		<li id="buttomContent1">
			<button id="btnConsultar">Consultar</button>
		</li>
		<li>
			<form action="/pdf/StockProducto/" method="post" target="_blank">
				<input type="submit" value="ver en pdf" id="mostrarPDF">
				<input type="hidden" id="idAlmacen"  name="idAlmacen">
				<input type="hidden" id="idProducto"  name="idProducto">
				<input type="hidden" id="idLinea" name="idLinea">
				<input type="hidden" id="idSubLinea" name="idSubLinea">
			</form>
		</li>
	</ul>
</fieldset>
<table id="dataGridReport">
	<thead>
		<tr>
			<th data-field="codigo">C&oacute;digo</th>
			<th data-field="nompro">Descripc&oacute;n</th>
			<th data-field="nomalm">Almacen</th>
			<th data-field="nomlin">Linea</th>
			<th data-field="unidadmedida">Unidad Medida</th>
			<th data-field="preciolista">Precio Lista(S/.)</th>
			<th data-field="preciolistadolares">Precio Lista(US $)</th>
			<th data-field="stockactual">Stock Actual</th>
			<th data-field="stockdisponible">Stock Disponible</th>
		</tr>
	</thead>
</table>