
<div id="listados">
<h2>Seguridad: Tranporte
</h2>
<br>

<form method="POST" action="/transporte/busca/">
<div id="busqueda">
		Busqueda: <br>
		<input type="text" id="txtBusqueda" name="txtBusqueda" size="50px" value="<?php echo $retorno;?>">
		<input type="submit" value="Ver">
</div>
</form>
<form method="POST" action="/transporte/lista/">
		<input type="submit" value="Cancelar">
</form>

<table>
	<thead>
		<tr>
			<th colspan="5">Listado de transporte</th>
			<th><a href="/transporte/nuevo">
					<img src="/imagenes/iconos/nuevo.gif">
				</a></th>
		</tr>
		<tr>
			<th>Id</th>
			<th>Nombre</th>
			<th>Dirección</th>
			<th>Ruc</th>
			<th>Telefono</th>
			<th>Acciones</th>

		</tr>
	</thead>
	<tbody>
		<?php
		$Ttransporte=sizeof($transporte);
		for($i=0;$i<$Ttransporte;$i++){
			if($transporte[$i]['estado']==0){
				$claseinactivo="class=\"inactivo\"";
			}else{
				$claseinactivo="";
			}
			
		$fila="<tr ".$claseinactivo.">";
			$fila.="<td><a href=\"/transporte/editar/".$transporte[$i]['idtransporte']."\">".STRTOUPPER($transporte[$i]['idtransporte'])."</a></td>";
			$fila.="<td>".$transporte[$i]['trazonsocial']."</td>";
			$fila.="<td>".$transporte[$i]['tdireccion']."</td>";
			$fila.="<td>".$transporte[$i]['truc']."</td>";
			$fila.="<td>".$transporte[$i]['ttelefono']."</td>";			
			$fila.="<td width=\"100px\">
						<a href=\"/transporte/editar/".$transporte[$i]['idtransporte']."\" ><img src=\"/imagenes/iconos/editar.gif\"></a>
						<a href=\"/transporte/eliminar/".$transporte[$i]['idtransporte']."\" ><img src=\"/imagenes/iconos/eliminar.gif\"></a>";
			$fila.="</td>";
		$fila.="</tr>";
		echo $fila;
		unset($fila);
		}
		?>	
	</tbody>
	<tfoot>
		<tr><td colspan="7" align="center">
		<?php
				$pagina=$_REQUEST['id'];
				if ($blockpaginas*10<$paginacion) {
					$blockpaginas=$blockpaginas+1;
				}else{
					$blockpaginas=$blockpaginas;
				}

				if ($pagina>1) 
				{
					echo "<a href=\"/transporte/busca/".($pagina-1)."\"> "."Anterior"." </a>";
				}
				
				for ($i=1; $i <=$blockpaginas ; $i++) { 
					$max=$i*10;

					for ($min=$max-9; $min <=$max ; $min++) { 
						if ($pagina>=$max-9 && $pagina<=$max && $paginacion>=$min) {
							if ($pagina==$min) {
								echo "<a clas='permanente' href=\"/transporte/busca/".($min)."\"> <b style='color:blue;'>".($min)." </b></a>";
							}else{
								echo "<a clas='permanente' href=\"/transporte/busca/".($min)."\"> ".($min)." </a>";
							}
						}
					}
				}

				if ($pagina<$paginacion && !empty($pagina)) 
				{
					echo "<a href=\"/transporte/busca/".($pagina+1)."\"> "."Siguiente"." </a>";
				}
				echo 'Total de registros: '.$totregistros;

		?>
		
		</tr>
	</tfoot>
</table>
</div>