<h2>Mantenimiento: Nuevo <?php echo $titulo ?></h2>
<input type="hidden" value="<?php echo $titulo; ?>" id="controller">
<script type="text/javascript">
	$(document).ready(function(){
		controller=$('#controller').val();
		var valor=true;
		$('#cancelar').click(function(e){
			e.preventDefault();
			window.location='/'+controller+'/lista';
		});

		$('#grabar').click(function(e){
			verificar();
			if (valor==false) {
				e.preventDefault();
			}
		});

		

		function verificar(){
			$('.numeric').each(function(){
				valor=$(this).val();
				if (valor>100) {
					valor=false;
				}else{
					valor true;
				}
			});
		}
	});
</script>
<fieldset>
	<form action="/<?php echo $titulo; ?>/grabar">
		<ul class="inline-block">
			<?php for ($i=1; $i <11 ; $i++) { ?>
				<li>
					<label><?php echo 'Descuento N° '.$i; ?></label>
					<input class="numeric " maxlength="3" type="text" name="<?php echo $titulo."[d".$i."]"; ?>" value="0">
				</li>
			<?php } ?>
			
			<li>
				<input type="submit" value="Grabar" id="grabar">
				<button id="cancelar">Cancelar</button>
			</li>
		</ul>

	</form>
</fieldset>