<h2>Mantenimiento: Editar Tipo Documento</h2>
<input type="hidden" value="<?php echo $titulo; ?>" id="controller">
<script type="text/javascript">
	$(document).ready(function(){
		controller=$('#controller').val();
		$('#cancelar').click(function(e){
			e.preventDefault();
			window.location='/'+controller+'/lista';
		});
	});
</script>

<fieldset>
	<form action="/<?php echo $titulo; ?>/actualizar" method="post">
		<ul class="inline-block">
			<li>
				<input type="hidden" value="<?php echo $data[0]['iddocumentotipo']; ?>" name="idobjeto">
				<label>Codigo</label>
				<input readonly type="text" size="10" name="<?php echo $titulo.'[codigotipodocumento]'; ?>"  value="<?php echo $data[0]['codigotipodocumento'] ?>" required>
			</li>
			<li>
				<label>Nombre</label>
				<input required type="text" size="40" name="<?php echo $titulo.'[nombre]'; ?>"  value="<?php echo $data[0]['nombre'] ?>" required>
			</li>
			
			<li>
				<input type="submit" value="Grabar">
				<button id="cancelar">Cancelar</button>
			</li>
		</ul>

	</form>
</fieldset>