<h2>Mantenimiento: Nuevo <?php echo $titulo ?></h2>
<input type="hidden" value="<?php echo $titulo; ?>" id="controller">
<script type="text/javascript">
	$(document).ready(function(){
		controller=$('#controller').val();
		$('#cancelar').click(function(e){
			e.preventDefault();
			window.location='/'+controller+'/lista';
		});
	});
</script>
<?php 
	$cantidadBanco=count($banco);
	$cantidadEmpresa=count($empresa);
 ?>
<fieldset>
	<form action="/<?php echo $titulo; ?>/grabar">
		<ul class="inline-block">
			<li>
				<label>Codigo</label>
				<input required type="text" name="<?php echo $titulo.'[codigo]'; ?>">
			</li>
			<li>
				<label>Nombre</label>
				<input required type="text" name="<?php echo $titulo.'[descripcion]'; ?>">
				
			</li>
			
			<li>
				<input type="submit" value="Grabar">
				<button id="cancelar">Cancelar</button>
			</li>
		</ul>

	</form>
</fieldset>